### ISSUE TITLE
Error when following the example

### ISSUE THREAD

**Issue by alanb1501** [kingsquare/node-livedocx#1]
I get the following error:

`Error: soap:Server: Server was unable to process request. --->Request for principal permission failed.: [object Object]`

I obviously use my own creds (valid).

According to livedocx, it's something to do with cookies not being enabled?

**Comment by Reggino** [comment]
Thanks for the report.

It seems the guys at LiveDocx (Text Control) have changed the way they handle cookies, sessions and authentication. Node.js lacks a normal SOAP client and the available ones don't support cookies as far as i can see. 

Anyway, i've hacked cookie-support into the current client, so if you'd update the code it should work fine again. 

Thanks again

Tim

**Comment by bkuchuk** [comment]
Same problem.
Something went wrong! [Error: soap:Server: Server was unable to process request.-->The user name/password combination is not valid.: [object Object]]

SoapUI is able to run the LogIn request without any problems.
